### PR TITLE
Add support for truly values

### LINKED ISSUE #17: Can't distinguish between a lack of value and an empty value
Given these urls:

* `http://example.com`
* `http://example.com?foo`
* `http://example.com?foo=`

evaluating `Url.queryString("foo")` gives identical result: `""`.

I expect this behavior instead:

* `http://example.com` -- `false` or `null` or `undefined`
* `http://example.com?foo` -- `true`
* `http://example.com?foo=` -- `""`

This is a major bug to me. Consider this current behavior:

```js
// Given URL http://example.com
const foo = Url.queryString("foo");
Url.updateSearchParam("foo", foo);
// Now the URL is different from what it was initially, even though we set the same value as we got.
```

### PR DESCRIPTION
**Pull request by IonicaBizau**
- Parse truly values in querystring (e.g. ?bar&foo=42 => bar is `true`)
 - Stringify truly values ({ bar: true, foo: 42 } => foo=42&bar)
 - Small syntax changes.
 - Return undefined for fields that do not exist in the querystring snippet.

Fixes #17. :tada:

### CODE REVIEW

**Comment by IonicaBizau** [comment]
@lolmaus Enjoy! Can you test this? :construction_worker:

**Comment by lolmaus** [comment]
For query `?foo&bar`, `Url.queryString('foo')` yields `true`.
But for query `?foo`, `Url.queryString('foo')` yields `undefined`.

image

**Comment by IonicaBizau** [comment]
@lolmaus Oh, good point. Tests will probably come later. This is just a quick fix. :smile: 

<sub>Removed the image from your comment. Without the popular f* word here.</sub>

**Comment by IonicaBizau** [comment]
@lolmaus Addressed in https://github.com/jillix/url.js/commit/9d1b1bfd721144ea7de64b033e08c43875350134. Can you test again? :smile:

**Comment by lolmaus** [comment]
Works for me! :+1:

**Comment by IonicaBizau** [comment]
@lolmaus Added tests :joy:

**Comment by lolmaus** [comment]
Yikes, custom test runner, custom assertion library!

wut

**Comment by lolmaus** [comment]
Seriously though, your tests seem to be order-dependent. I would prefer `beforeEach` and `afterEach` setting up and tearing down the scene for every individual test.

Also, you're never checking the actual page URL. You use the library to do something, then use the same library to assert the result. It's a shortcut you don't want to take in tests.

**Comment by IonicaBizau** [comment]
@lolmaus I agree the tests can be improved. Regarding the test library, it's the minimal thing I use for testing. I never liked these huge and popular frameworks. They are heavy enough to decide not to use them.

> Seriously though, your tests seem to be order-dependent.

Yes, they are. In this context it doesn't make sense to reload the page every time when running a test.

> Also, you're never checking the actual page URL. You use the library to do something, then use the same library to assert the result.

This is a good point. :+1:

**Pull request merged**
